server:
  port: 9000

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/bigdata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: tokings
    password: 19890625
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapping/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.hncy58.bigdata.gateway.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

zuul:
  add-host-header: true
  host:
    #连接超时
    connect-timeout-millis: 120000
    #读写超时
    socket-timeout-millis: 120000
  sensitiveHeaders:
  # 路由配置
  routes:
    baidu:
      path: /baidu/**
      url: http://www.baidu.com
    api-local:
      path: /local/**
      url: http://localhost:9000
    api-1:
      path: /user/**
      url: http://localhost:8081
    api-2:
      path: /personas/**
      url: http://localhost:8082

  # 限流配置
  ratelimit:
    key-prefix: pig-ratelimite 
    enabled: true 
    repository: IN_MEMORY 
    behind-proxy: true
    policies:
      api-1:
        limit: 2
        quota: 1
        refresh-interval: 3
        type:
          - url
      api-2:
        limit: 2
        quota: 1
        refresh-interval: 3
        type:
          - url
      baidu:
        limit: 1
        quota: 1
        refresh-interval: 10
        type:
          - url

# 反向代理配置
#api-1:
#  ribbon:
#    listOfServers: localhost:8081
#api-2:
#  ribbon:
#    listOfServers: localhost:8082
